### ISSUE TITLE
Upgrade to Nativescript 7

### ISSUE THREAD

**Issue by crechberger** [EddyVerbruggen/nativescript-keyboard-toolbar#11]
Hey,

Nativescript recenlty introcuded some big changes (for example they changed the compiler option from "ES-5" to "ES2017"). It would be great if you could bring the whole project up to date. 

Here's the url with all the instructions: [](https://nativescript.org/blog/nativescript-7-for-plugin-authors/)

Thank you :)

**Comment by miladfm** [comment]
There is an error in Nativescript 7


```
typeError: Class constructor ContentView cannot be invoked without 'new'
    at ToolbarBase [as constructor] (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:178157:47)
    at new Toolbar (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:178223:28)
    at ViewUtil.createView (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:93506:22)
    at EmulatedRenderer.createElement (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:93706:30)
    at EmulatedRenderer.createElement (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:93923:28)
    at BaseAnimationRenderer.createElement (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:82382:30)
    at elementCreate (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:50479:25)
    at Module.ɵɵelementStart (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:58110:43)
    at TopicEditContentSectionSubTitleComponent_Template (file:///data/user/0/org.nativescript.nextweb/files/app/3.js:5731:69)
    at executeTemplate (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:50785:9)
    at renderView (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:50594:13)
    at renderComponent (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:51848:5)
    at renderChildComponents (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:50468:9)
    at renderView (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:50619:13)
    at TemplateRef.createEmbeddedView (file:///data/user/0/org.nativescript.nextweb/files/app/vendor.js:53388:17)"
```

**Comment by ptomasini** [comment]
No update about NS 7 compatibility?

**Comment by JJVetter** [comment]
+1 to upgrade to NS7

**Comment by vallemar** [comment]
+1

**Comment by shaltie** [comment]
Please +1
This will be very helpful. Thanx!

**Comment by jarrodwhitley** [comment]
Does anyone know of an alternative? Preferably something that uses `@nativescript/core` and not `tns-core-modules`
